version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Or a more recent LTS version if available
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps
      # Remove --legacy-peer-deps if possible. Address peer dependency warnings instead.
      # If you must use it, understand the implications.
  build:
    commands:
      - echo "Building Angular application..."
      - npm run build --prod # Build for production
  post_build: # Add a post_build phase for zipping
    commands:
      - echo "Zipping the build output..."
      - zip -r my-app.zip dist # Creates a zip of the dist folder
artifacts:
  files:
    - my-app.zip # Zip file is the artifact
  discard-paths: yes # Correct setting: Discard directory structure in artifact
#cache is good practice
cache:
  paths:
    - node_modules/**/*
