version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility

  build:
    commands:
      - echo "Building Angular application..."
      - npm run build --prod  # Build for production
      - echo "Zipping the build output..."
      - zip -r angular-build.zip dist/

artifacts:
  files:
    - angular-build.zip
  base-directory: .  # The location where the zip file is created
  discard-paths: no
