version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility

  build:
    commands:
      - echo "Building Angular application..."
      - npm run build --prod  # Build for production
      - echo "Zipping the build output..."
      - zip -r angular-build.zip 
      
post_build:
  commands:
    - echo "Verifying zip file before upload..."
    - ls -lh angular-build.zip  # List files to confirm zip exists
    - aws s3 cp /codebuild/output/src1701380961/src/dist/aqua-select/angular-build.zip  s3://aquaflow195/dist  # Upload to S3
    
artifacts:
  files:
    - "**/*"  # Include all files in the working directory
  base-directory: dist  # Base directory to include files from
  discard-paths: no  # Keep the original folder structure
