version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility
      - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
