version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility

  build:
     commands:
       - echo "Building Angular application..."
       - npm run build --prod  # Build for production
       - echo "Zipping the build output..."
       - cd dist  # Move to the Angular dist folder
       - zip -r ../angular-build.zip .  # Create a zip archive of the build output
       - cd ..  # Go back to the root directory

 artifacts:
   files:
      - angular-build.zip
   #  - '**/*'  # Include all necessary files
   base-directory: .  # Change this if your Angular app outputs to a different folder
   discard-paths: no
 
