version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility

#   build:
#     commands:
#       - echo "Building Angular application..."
#       - npm run build --prod  # Build for production



# artifacts:
#   files:
#     - '**/*'  # Include all necessary files
#   base-directory: dist  # Change this if your Angular app outputs to a different folder
#   discard-paths: no
  build:
    commands:
      - echo "Building Angular application..."
      - npm run build --prod  # Build for production
      - export BUILD_VERSION=$(date +%Y%m%d%H%M%S)  # Generate a timestamped version
      - echo "Build Version: $BUILD_VERSION"
      - mkdir -p build-artifacts
      - cp -r dist/* build-artifacts/
      - cd build-artifacts
      - zip -r "../angular-build-$BUILD_VERSION.zip" .  # Create a ZIP file with a versioned name
      - cd ..

artifacts:
  files:
    - 'angular-build-*.zip'  # Upload the versioned ZIP file
  discard-paths: no
