version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility

  build:
    commands:
      - echo "Building Angular application..."
      - npm run build --prod  # Build for production
      - echo "Zipping the build output..."
      - zip -r angular-build.zip dist/aqua-select/
      
post_build:
  commands:
    - echo "Verifying zip file before upload..."
    - ls -lh angular-build.zip  # List files to confirm zip exists
    - mv angular-build.zip /codebuild/output/src107010302/src/  # Move to expected directory
    - aws s3 cp /codebuild/output/src107010302/src/angular-build.zip s3://aquaflow195/
    
artifacts:
  files:
    - angular-build.zip
  base-directory: /codebuild/output/src107010302/src/ 
  discard-paths: yes
