version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a compatible Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install -g npm@latest   # Upgrade npm to the latest version
      - npm install js-yaml@latest --save  # Fix js-yaml issue
      - npm install --legacy-peer-deps  # Install dependencies with Angular version compatibility

  build:
    commands:
      - echo "Building Angular application..."
      - npm run build --prod  # Build for production

artifacts:
  files:
    - '**/*'  # Include all necessary files
  base-directory: dist  # Change this if your Angular app outputs to a different folder
  discard-paths: no
