# Stage 1: Build the Angular application
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve the Angular app using Nginx
FROM nginx:alpine

# Copy the built Angular files to the Nginx directory
COPY --from=build /app/dist/YOUR_PROJECT_NAME /usr/share/nginx/html

# Expose port 80 for the container
EXPOSE 90

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
