services:
  aqua-select:
    container_name: aqua-selectcontainer
    build: .
    image: aqua-select:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
